"""71 brand design tokens — extracted from VoltAgent/awesome-design-md.

Auto-generated. Re-run agent to refresh after _brand-md/ updates.
"""

BRAND_TOKENS = {
    "airbnb": {
        "primary": "#ff5a5f",
        "primary_active": "#e63946",
        "canvas": "#ffffff",
        "surface_card": "#f7f7f7",
        "ink": "#222222",
        "body": "#484848",
        "muted": "#717171",
        "headline_font": "Cereal, -apple-system, BlinkMacSystemFont, sans-serif",
        "body_font": "Cereal, -apple-system, BlinkMacSystemFont, sans-serif",
        "signature": "밝은 빨강 + 캘리포니아 따뜻함 = 즐거운 여행 기분",
        "cluster": "colorful",
    },
    "airtable": {
        "primary": "#0080ff",
        "primary_active": "#0052cc",
        "canvas": "#ffffff",
        "surface_card": "#f5f6f7",
        "ink": "#000000",
        "body": "#303030",
        "muted": "#595959",
        "headline_font": "Inter, system-ui, sans-serif",
        "body_font": "Inter, system-ui, sans-serif",
        "signature": "하늘 파랑 + 미니멀 격자 = 협업의 명확함",
        "cluster": "corporate-blue",
    },
    "apple": {
        "primary": "#000000",
        "primary_active": "#333333",
        "canvas": "#ffffff",
        "surface_card": "#f5f5f5",
        "ink": "#000000",
        "body": "#1d1d1f",
        "muted": "#86868b",
        "headline_font": "SF Pro Display, -apple-system, sans-serif",
        "body_font": "SF Pro Display, -apple-system, sans-serif",
        "signature": "검은색 + 공허한 공간 = 세련된 극단주의",
        "cluster": "dark-minimal",
    },
    "binance": {
        "primary": "#f3ba2f",
        "primary_active": "#d4a017",
        "canvas": "#0b0e11",
        "surface_card": "#1e2329",
        "ink": "#ffffff",
        "body": "#e0e0e0",
        "muted": "#a8a8a8",
        "headline_font": "Inter, -apple-system, sans-serif",
        "body_font": "Inter, -apple-system, sans-serif",
        "signature": "금색 + 검은색 배경 = 암호 거래의 신뢰",
        "cluster": "dark-minimal",
    },
    "bmw": {
        "primary": "#0066b2",
        "primary_active": "#004488",
        "canvas": "#ffffff",
        "surface_card": "#f0f0f0",
        "ink": "#000000",
        "body": "#222222",
        "muted": "#666666",
        "headline_font": "BMW, -apple-system, sans-serif",
        "body_font": "BMW, -apple-system, sans-serif",
        "signature": "깊은 파랑 + 독일식 정밀 = 럭셔리 엔지니어링",
        "cluster": "corporate-blue",
    },
    "bmw-m": {
        "primary": "#dd0000",
        "primary_active": "#bb0000",
        "canvas": "#ffffff",
        "surface_card": "#f2f2f2",
        "ink": "#000000",
        "body": "#1a1a1a",
        "muted": "#555555",
        "headline_font": "BMW, -apple-system, sans-serif",
        "body_font": "BMW, -apple-system, sans-serif",
        "signature": "레이싱 빨강 + 고급 추상 = 성능 에너지",
        "cluster": "neon-acid",
    },
    "bugatti": {
        "primary": "#d21027",
        "primary_active": "#9b0019",
        "canvas": "#ffffff",
        "surface_card": "#f1f1f1",
        "ink": "#000000",
        "body": "#1a1a1a",
        "muted": "#4a4a4a",
        "headline_font": "Bugatti, Futura, sans-serif",
        "body_font": "Bugatti, Futura, sans-serif",
        "signature": "버간디 + 프랑스식 우아함 = 최고급 자동차",
        "cluster": "neon-acid",
    },
    "cal": {
        "primary": "#4f46e5",
        "primary_active": "#4338ca",
        "canvas": "#ffffff",
        "surface_card": "#f3f4f6",
        "ink": "#000000",
        "body": "#374151",
        "muted": "#9ca3af",
        "headline_font": "Inter, system-ui, sans-serif",
        "body_font": "Inter, system-ui, sans-serif",
        "signature": "깊은 보라 + 깔끔함 = 일정 관리 수련",
        "cluster": "corporate-blue",
    },
    "claude": {
        "primary": "#cc785c",
        "primary_active": "#a9583e",
        "canvas": "#faf9f5",
        "surface_card": "#efe9de",
        "ink": "#141413",
        "body": "#3d3d3a",
        "muted": "#6c6a64",
        "headline_font": "Copernicus, Tiempos Headline, serif",
        "body_font": "StyreneB, Inter, sans-serif",
        "signature": "크림 + 산호 + 세리프 = 따뜻한 편집 분위기",
        "cluster": "warm-editorial",
    },
    "clay": {
        "primary": "#7c3aed",
        "primary_active": "#6d28d9",
        "canvas": "#ffffff",
        "surface_card": "#f3f4f6",
        "ink": "#111827",
        "body": "#374151",
        "muted": "#9ca3af",
        "headline_font": "Inter, system-ui, sans-serif",
        "body_font": "Inter, system-ui, sans-serif",
        "signature": "보라 + AI 창의력 = 점토처럼 유연",
        "cluster": "corporate-blue",
    },
    "clickhouse": {
        "primary": "#ffd700",
        "primary_active": "#ffb700",
        "canvas": "#131820",
        "surface_card": "#1f2430",
        "ink": "#ffffff",
        "body": "#d0d8e0",
        "muted": "#8a92a0",
        "headline_font": "Inter, system-ui, sans-serif",
        "body_font": "Inter, system-ui, sans-serif",
        "signature": "황금 + 다크 = 데이터 속도의 빛",
        "cluster": "dark-minimal",
    },
    "cohere": {
        "primary": "#00b4d8",
        "primary_active": "#0099bb",
        "canvas": "#ffffff",
        "surface_card": "#f0f9fc",
        "ink": "#0d1b2a",
        "body": "#1b4965",
        "muted": "#5a7d99",
        "headline_font": "IBM Plex Sans, system-ui, sans-serif",
        "body_font": "IBM Plex Sans, system-ui, sans-serif",
        "signature": "밝은 청록 + 신뢰 = AI 언어 모델",
        "cluster": "corporate-blue",
    },
    "coinbase": {
        "primary": "#0052ff",
        "primary_active": "#0041cc",
        "canvas": "#ffffff",
        "surface_card": "#f5f7f9",
        "ink": "#0f1419",
        "body": "#424245",
        "muted": "#999999",
        "headline_font": "Inter, system-ui, sans-serif",
        "body_font": "Inter, system-ui, sans-serif",
        "signature": "신뢰 파랑 + 간결함 = 암호 금융",
        "cluster": "corporate-blue",
    },
    "composio": {
        "primary": "#ff6b35",
        "primary_active": "#d64429",
        "canvas": "#ffffff",
        "surface_card": "#f7f7f7",
        "ink": "#1a1a1a",
        "body": "#4a4a4a",
        "muted": "#999999",
        "headline_font": "Poppins, system-ui, sans-serif",
        "body_font": "Poppins, system-ui, sans-serif",
        "signature": "오렌지 + 개발자 도구 = 자동화 액션",
        "cluster": "colorful",
    },
    "cursor": {
        "primary": "#00d9ff",
        "primary_active": "#00b8d9",
        "canvas": "#0a0a0a",
        "surface_card": "#161616",
        "ink": "#ffffff",
        "body": "#e0e0e0",
        "muted": "#808080",
        "headline_font": "Inter, system-ui, sans-serif",
        "body_font": "Inter, system-ui, sans-serif",
        "signature": "밝은 청록 + 어두운 배경 = AI 코드 에디터",
        "cluster": "dark-minimal",
    },
    "elevenlabs": {
        "primary": "#9d5bd2",
        "primary_active": "#7d3fa0",
        "canvas": "#ffffff",
        "surface_card": "#f5f3f7",
        "ink": "#1a1a1a",
        "body": "#3a3a3a",
        "muted": "#999999",
        "headline_font": "Inter, system-ui, sans-serif",
        "body_font": "Inter, system-ui, sans-serif",
        "signature": "보라 + 음성 합성 = 창의적 AI",
        "cluster": "colorful",
    },
    "expo": {
        "primary": "#000000",
        "primary_active": "#333333",
        "canvas": "#ffffff",
        "surface_card": "#f8f8f8",
        "ink": "#000000",
        "body": "#333333",
        "muted": "#999999",
        "headline_font": "Inter, system-ui, sans-serif",
        "body_font": "Inter, system-ui, sans-serif",
        "signature": "검은색 + React Native = 오픈소스 명확함",
        "cluster": "dark-minimal",
    },
    "ferrari": {
        "primary": "#dc143c",
        "primary_active": "#8b0000",
        "canvas": "#ffffff",
        "surface_card": "#f5f5f5",
        "ink": "#000000",
        "body": "#1a1a1a",
        "muted": "#4a4a4a",
        "headline_font": "Ferrari, serif",
        "body_font": "Ferrari, sans-serif",
        "signature": "페라리 레드 + 이탈리아 고급 = 속도",
        "cluster": "neon-acid",
    },
    "figma": {
        "primary": "#18a0fb",
        "primary_active": "#0d66d0",
        "canvas": "#ffffff",
        "surface_card": "#f3f3f3",
        "ink": "#0d0d0d",
        "body": "#333333",
        "muted": "#999999",
        "headline_font": "Inter, system-ui, sans-serif",
        "body_font": "Inter, system-ui, sans-serif",
        "signature": "밝은 파랑 + 협업 UI = 디자인 플랫폼",
        "cluster": "corporate-blue",
    },
    "framer": {
        "primary": "#0099ff",
        "primary_active": "#0077cc",
        "canvas": "#ffffff",
        "surface_card": "#f5f5f5",
        "ink": "#000000",
        "body": "#333333",
        "muted": "#999999",
        "headline_font": "Inter, system-ui, sans-serif",
        "body_font": "Inter, system-ui, sans-serif",
        "signature": "밝은 파랑 + 애니메이션 = 모션 디자인",
        "cluster": "corporate-blue",
    },
    "hashicorp": {
        "primary": "#1d1d1b",
        "primary_active": "#2a2a27",
        "canvas": "#ffffff",
        "surface_card": "#f9f9f8",
        "ink": "#1d1d1b",
        "body": "#3a3a37",
        "muted": "#757570",
        "headline_font": "Helvetica, Arial, sans-serif",
        "body_font": "Helvetica, Arial, sans-serif",
        "signature": "토크 갈색 + 인프라 신뢰 = DevOps",
        "cluster": "dark-minimal",
    },
    "ibm": {
        "primary": "#161616",
        "primary_active": "#262626",
        "canvas": "#ffffff",
        "surface_card": "#f4f4f4",
        "ink": "#161616",
        "body": "#525252",
        "muted": "#8d8d8d",
        "headline_font": "IBM Plex Sans, system-ui, sans-serif",
        "body_font": "IBM Plex Sans, system-ui, sans-serif",
        "signature": "IBM 어두운 회색 + 기업 신뢰 = 엔터프라이즈",
        "cluster": "dark-minimal",
    },
    "intercom": {
        "primary": "#0052cc",
        "primary_active": "#0041a8",
        "canvas": "#ffffff",
        "surface_card": "#f5f6f7",
        "ink": "#000000",
        "body": "#2c3e50",
        "muted": "#8b95a7",
        "headline_font": "Inter, system-ui, sans-serif",
        "body_font": "Inter, system-ui, sans-serif",
        "signature": "깊은 파랑 + 고객 소통 = CRM",
        "cluster": "corporate-blue",
    },
    "kraken": {
        "primary": "#520dc2",
        "primary_active": "#3d0a8f",
        "canvas": "#0a0e27",
        "surface_card": "#1a1f3a",
        "ink": "#ffffff",
        "body": "#d0d5e0",
        "muted": "#808a9a",
        "headline_font": "Inter, system-ui, sans-serif",
        "body_font": "Inter, system-ui, sans-serif",
        "signature": "보라 + 깔짝이 바다 = 암호 거래",
        "cluster": "dark-minimal",
    },
    "lamborghini": {
        "primary": "#ffeb00",
        "primary_active": "#ffcc00",
        "canvas": "#ffffff",
        "surface_card": "#f5f5f5",
        "ink": "#000000",
        "body": "#1a1a1a",
        "muted": "#4a4a4a",
        "headline_font": "Lamborghini, sans-serif",
        "body_font": "Lamborghini, sans-serif",
        "signature": "황금 + 이탈리아 럭셔리 = 슈퍼카",
        "cluster": "neon-acid",
    },
    "linear-app": {
        "primary": "#5e56e6",
        "primary_active": "#4c47d8",
        "canvas": "#ffffff",
        "surface_card": "#f7f7f7",
        "ink": "#000000",
        "body": "#404040",
        "muted": "#909090",
        "headline_font": "Inter, system-ui, sans-serif",
        "body_font": "Inter, system-ui, sans-serif",
        "signature": "인디고 + 극단 미니멀 = 이슈 추적",
        "cluster": "corporate-blue",
    },
    "lovable": {
        "primary": "#ff4d6d",
        "primary_active": "#d63750",
        "canvas": "#ffffff",
        "surface_card": "#f7f7f7",
        "ink": "#1a1a1a",
        "body": "#404040",
        "muted": "#909090",
        "headline_font": "Poppins, system-ui, sans-serif",
        "body_font": "Poppins, system-ui, sans-serif",
        "signature": "핑크 + 사랑 웹앱 = 빠른 제작",
        "cluster": "colorful",
    },
    "mastercard": {
        "primary": "#eb001b",
        "primary_active": "#c20018",
        "canvas": "#ffffff",
        "surface_card": "#f5f5f5",
        "ink": "#000000",
        "body": "#333333",
        "muted": "#999999",
        "headline_font": "Mastercard, sans-serif",
        "body_font": "Mastercard, sans-serif",
        "signature": "마스터카드 레드 + 금융 신뢰 = 결제",
        "cluster": "neon-acid",
    },
    "meta": {
        "primary": "#0084f3",
        "primary_active": "#0055d9",
        "canvas": "#ffffff",
        "surface_card": "#f0f2f5",
        "ink": "#000000",
        "body": "#50545b",
        "muted": "#8a8d91",
        "headline_font": "Helvetica, Arial, sans-serif",
        "body_font": "Helvetica, Arial, sans-serif",
        "signature": "페이스북 파랑 + 소셜 네트워크 = 연결",
        "cluster": "corporate-blue",
    },
    "minimax": {
        "primary": "#6b4ce6",
        "primary_active": "#5538cc",
        "canvas": "#ffffff",
        "surface_card": "#f5f5f5",
        "ink": "#1a1a1a",
        "body": "#404040",
        "muted": "#909090",
        "headline_font": "Inter, system-ui, sans-serif",
        "body_font": "Inter, system-ui, sans-serif",
        "signature": "보라 + AI 텍스트 생성 = 미니멀 도구",
        "cluster": "corporate-blue",
    },
    "mintlify": {
        "primary": "#00d084",
        "primary_active": "#00a366",
        "canvas": "#ffffff",
        "surface_card": "#f0fef7",
        "ink": "#000000",
        "body": "#3a3a3a",
        "muted": "#999999",
        "headline_font": "Inter, system-ui, sans-serif",
        "body_font": "Inter, system-ui, sans-serif",
        "signature": "민트 녹색 + 문서 생성 = 신선함",
        "cluster": "colorful",
    },
    "miro": {
        "primary": "#ffac45",
        "primary_active": "#ff8c1f",
        "canvas": "#ffffff",
        "surface_card": "#faf8f5",
        "ink": "#000000",
        "body": "#323232",
        "muted": "#999999",
        "headline_font": "Rubik, system-ui, sans-serif",
        "body_font": "Rubik, system-ui, sans-serif",
        "signature": "주황색 + 화이트보드 + 협업 = 창의성",
        "cluster": "colorful",
    },
    "mistral-ai": {
        "primary": "#2f81f7",
        "primary_active": "#1b5cdb",
        "canvas": "#ffffff",
        "surface_card": "#f5f7f9",
        "ink": "#000000",
        "body": "#2c3e50",
        "muted": "#8b95a7",
        "headline_font": "Inter, system-ui, sans-serif",
        "body_font": "Inter, system-ui, sans-serif",
        "signature": "파랑 + 프랑스 AI = 개방형 언어 모델",
        "cluster": "corporate-blue",
    },
    "mongodb": {
        "primary": "#10aa50",
        "primary_active": "#078a3b",
        "canvas": "#ffffff",
        "surface_card": "#f8f9fa",
        "ink": "#000000",
        "body": "#333333",
        "muted": "#999999",
        "headline_font": "ProximaNova, system-ui, sans-serif",
        "body_font": "ProximaNova, system-ui, sans-serif",
        "signature": "네온 녹색 + 데이터베이스 = 유연한 문서",
        "cluster": "neon-acid",
    },
    "nike": {
        "primary": "#000000",
        "primary_active": "#1a1a1a",
        "canvas": "#ffffff",
        "surface_card": "#f5f5f5",
        "ink": "#000000",
        "body": "#222222",
        "muted": "#666666",
        "headline_font": "Futura, sans-serif",
        "body_font": "Futura, sans-serif",
        "signature": "검은색 + 스포츠 에너지 = 그냥 해",
        "cluster": "dark-minimal",
    },
    "notion": {
        "primary": "#000000",
        "primary_active": "#1a1a1a",
        "canvas": "#ffffff",
        "surface_card": "#f5f5f5",
        "ink": "#000000",
        "body": "#373737",
        "muted": "#999999",
        "headline_font": "Inter, system-ui, sans-serif",
        "body_font": "Inter, system-ui, sans-serif",
        "signature": "검은색 + 아이콘 = 올인원 워크스페이스",
        "cluster": "dark-minimal",
    },
    "nvidia": {
        "primary": "#76b900",
        "primary_active": "#5a8e00",
        "canvas": "#ffffff",
        "surface_card": "#f5f5f5",
        "ink": "#000000",
        "body": "#333333",
        "muted": "#999999",
        "headline_font": "NVIDIA, sans-serif",
        "body_font": "NVIDIA, sans-serif",
        "signature": "NVIDIA 초록 + GPU 성능 = 병렬 처리",
        "cluster": "colorful",
    },
    "ollama": {
        "primary": "#ff6b35",
        "primary_active": "#d64429",
        "canvas": "#1a1a1a",
        "surface_card": "#262626",
        "ink": "#ffffff",
        "body": "#d0d0d0",
        "muted": "#808080",
        "headline_font": "Inter, system-ui, sans-serif",
        "body_font": "Inter, system-ui, sans-serif",
        "signature": "주황색 + 로컬 LLM = 뜨거운 실행",
        "cluster": "dark-minimal",
    },
    "opencode-ai": {
        "primary": "#00d9ff",
        "primary_active": "#00b8d9",
        "canvas": "#0a0a0a",
        "surface_card": "#1a1a1a",
        "ink": "#ffffff",
        "body": "#d0d0d0",
        "muted": "#808080",
        "headline_font": "Inter, system-ui, sans-serif",
        "body_font": "Inter, system-ui, sans-serif",
        "signature": "청록색 + 오픈 코드 = AI 협력",
        "cluster": "dark-minimal",
    },
    "pinterest": {
        "primary": "#e60023",
        "primary_active": "#ad081b",
        "canvas": "#ffffff",
        "surface_card": "#f7f7f7",
        "ink": "#000000",
        "body": "#333333",
        "muted": "#999999",
        "headline_font": "Helvetica, Arial, sans-serif",
        "body_font": "Helvetica, Arial, sans-serif",
        "signature": "핀터레스트 빨강 + 영감 수집 = 비주얼",
        "cluster": "neon-acid",
    },
    "playstation": {
        "primary": "#003087",
        "primary_active": "#001a4d",
        "canvas": "#ffffff",
        "surface_card": "#f5f5f5",
        "ink": "#000000",
        "body": "#1a1a1a",
        "muted": "#4a4a4a",
        "headline_font": "PlayStation, sans-serif",
        "body_font": "PlayStation, sans-serif",
        "signature": "PS 파랑 + 게임 문화 = 플레이스테이션",
        "cluster": "corporate-blue",
    },
    "posthog": {
        "primary": "#1d2117",
        "primary_active": "#0f0f0a",
        "canvas": "#ffffff",
        "surface_card": "#f5f5f5",
        "ink": "#1d2117",
        "body": "#3a3a37",
        "muted": "#757570",
        "headline_font": "Inter, system-ui, sans-serif",
        "body_font": "Inter, system-ui, sans-serif",
        "signature": "어두운 모스 녹색 + 제품 분석 = 통찰",
        "cluster": "dark-minimal",
    },
    "raycast": {
        "primary": "#ff6363",
        "primary_active": "#e63946",
        "canvas": "#1a1a1a",
        "surface_card": "#262626",
        "ink": "#ffffff",
        "body": "#d0d0d0",
        "muted": "#808080",
        "headline_font": "Inter, system-ui, sans-serif",
        "body_font": "Inter, system-ui, sans-serif",
        "signature": "빨강 + 빠른 접근성 = Mac 램프",
        "cluster": "dark-minimal",
    },
    "renault": {
        "primary": "#004b7a",
        "primary_active": "#003a5c",
        "canvas": "#ffffff",
        "surface_card": "#f0f0f0",
        "ink": "#000000",
        "body": "#222222",
        "muted": "#666666",
        "headline_font": "Renault, sans-serif",
        "body_font": "Renault, sans-serif",
        "signature": "르노 파랑 + 프랑스식 자동차 = 혁신",
        "cluster": "corporate-blue",
    },
    "replicate": {
        "primary": "#ffffff",
        "primary_active": "#e0e0e0",
        "canvas": "#000000",
        "surface_card": "#1a1a1a",
        "ink": "#ffffff",
        "body": "#d0d0d0",
        "muted": "#808080",
        "headline_font": "Inter, system-ui, sans-serif",
        "body_font": "Inter, system-ui, sans-serif",
        "signature": "흰색 + 어두운 배경 = AI 모델 API",
        "cluster": "dark-minimal",
    },
    "resend": {
        "primary": "#000000",
        "primary_active": "#1a1a1a",
        "canvas": "#ffffff",
        "surface_card": "#f5f5f5",
        "ink": "#000000",
        "body": "#333333",
        "muted": "#999999",
        "headline_font": "Inter, system-ui, sans-serif",
        "body_font": "Inter, system-ui, sans-serif",
        "signature": "검은색 + 이메일 API = 현대식 발송",
        "cluster": "dark-minimal",
    },
    "revolut": {
        "primary": "#201a1a",
        "primary_active": "#0f0f0f",
        "canvas": "#ffffff",
        "surface_card": "#f5f5f5",
        "ink": "#201a1a",
        "body": "#3a3a3a",
        "muted": "#999999",
        "headline_font": "Inter, system-ui, sans-serif",
        "body_font": "Inter, system-ui, sans-serif",
        "signature": "짙은 갈색 + 핀테크 = 디지털 뱅킹",
        "cluster": "dark-minimal",
    },
    "runwayml": {
        "primary": "#00ffa3",
        "primary_active": "#00d986",
        "canvas": "#0a0a0a",
        "surface_card": "#1a1a1a",
        "ink": "#ffffff",
        "body": "#d0d0d0",
        "muted": "#808080",
        "headline_font": "Suisse BP, system-ui, sans-serif",
        "body_font": "Suisse BP, system-ui, sans-serif",
        "signature": "네온 초록 + AI 영상 = 창의적 도구",
        "cluster": "dark-minimal",
    },
    "sanity": {
        "primary": "#f03e2f",
        "primary_active": "#cc3122",
        "canvas": "#ffffff",
        "surface_card": "#f5f5f5",
        "ink": "#000000",
        "body": "#333333",
        "muted": "#999999",
        "headline_font": "Inter, system-ui, sans-serif",
        "body_font": "Inter, system-ui, sans-serif",
        "signature": "산티 주황 + 구조화된 콘텐츠 = CMS",
        "cluster": "colorful",
    },
    "sentry": {
        "primary": "#362d59",
        "primary_active": "#1a1726",
        "canvas": "#ffffff",
        "surface_card": "#f5f5f5",
        "ink": "#1a1726",
        "body": "#3a3a3a",
        "muted": "#999999",
        "headline_font": "Inter, system-ui, sans-serif",
        "body_font": "Inter, system-ui, sans-serif",
        "signature": "짙은 보라 + 오류 추적 = 신뢰성",
        "cluster": "dark-minimal",
    },
    "shopify": {
        "primary": "#96bf48",
        "primary_active": "#79a537",
        "canvas": "#ffffff",
        "surface_card": "#f6f6f6",
        "ink": "#202223",
        "body": "#626364",
        "muted": "#a6a8aa",
        "headline_font": "Shopify Sans, system-ui, sans-serif",
        "body_font": "Shopify Sans, system-ui, sans-serif",
        "signature": "Shopify 초록 + 이커머스 = 성장",
        "cluster": "colorful",
    },
    "slack": {
        "primary": "#36c5f0",
        "primary_active": "#1da1f2",
        "canvas": "#ffffff",
        "surface_card": "#f8f8f8",
        "ink": "#2c2d30",
        "body": "#616061",
        "muted": "#989899",
        "headline_font": "Slack Lato, system-ui, sans-serif",
        "body_font": "Slack Lato, system-ui, sans-serif",
        "signature": "슬랙 파랑 + 협업 채팅 = 연결",
        "cluster": "corporate-blue",
    },
    "spacex": {
        "primary": "#000000",
        "primary_active": "#1a1a1a",
        "canvas": "#ffffff",
        "surface_card": "#f5f5f5",
        "ink": "#000000",
        "body": "#1a1a1a",
        "muted": "#4a4a4a",
        "headline_font": "SpaceX, sans-serif",
        "body_font": "SpaceX, sans-serif",
        "signature": "검은색 + 우주 탐사 = 미래",
        "cluster": "dark-minimal",
    },
    "spotify": {
        "primary": "#1db954",
        "primary_active": "#1ed760",
        "canvas": "#121212",
        "surface_card": "#1e1e1e",
        "ink": "#ffffff",
        "body": "#d0d0d0",
        "muted": "#808080",
        "headline_font": "GothamPro, system-ui, sans-serif",
        "body_font": "GothamPro, system-ui, sans-serif",
        "signature": "Spotify 초록 + 음악 스트리밍 = 재생",
        "cluster": "dark-minimal",
    },
    "starbucks": {
        "primary": "#00704a",
        "primary_active": "#005237",
        "canvas": "#ffffff",
        "surface_card": "#f7f3e8",
        "ink": "#000000",
        "body": "#333333",
        "muted": "#999999",
        "headline_font": "Gotham, system-ui, sans-serif",
        "body_font": "Gotham, system-ui, sans-serif",
        "signature": "스타벅스 초록 + 커피 따뜻함 = 편안",
        "cluster": "warm-editorial",
    },
    "stripe": {
        "primary": "#533afd",
        "primary_active": "#2e2b8c",
        "canvas": "#ffffff",
        "surface_card": "#f6f9fc",
        "ink": "#0d253d",
        "body": "#273951",
        "muted": "#64748d",
        "headline_font": "sohne-var, SF Pro Display, sans-serif",
        "body_font": "sohne-var, SF Pro Display, sans-serif",
        "signature": "스트라이프 인디고 + 금융 신뢰 = 결제",
        "cluster": "corporate-blue",
    },
    "supabase": {
        "primary": "#3ecf8e",
        "primary_active": "#2bb877",
        "canvas": "#ffffff",
        "surface_card": "#f8f9fa",
        "ink": "#1a202c",
        "body": "#374151",
        "muted": "#9ca3af",
        "headline_font": "Inter, system-ui, sans-serif",
        "body_font": "Inter, system-ui, sans-serif",
        "signature": "수파베이스 초록 + 데이터베이스 = 오픈소스",
        "cluster": "colorful",
    },
    "superhuman": {
        "primary": "#ff5800",
        "primary_active": "#d63d00",
        "canvas": "#ffffff",
        "surface_card": "#f8f8f8",
        "ink": "#0d0d0d",
        "body": "#333333",
        "muted": "#999999",
        "headline_font": "Recoleta, serif",
        "body_font": "Inter, system-ui, sans-serif",
        "signature": "스퍼휴먼 주황 + 이메일 클라이언트 = 속도",
        "cluster": "colorful",
    },
    "tesla": {
        "primary": "#cc0000",
        "primary_active": "#990000",
        "canvas": "#ffffff",
        "surface_card": "#f5f5f5",
        "ink": "#000000",
        "body": "#1a1a1a",
        "muted": "#4a4a4a",
        "headline_font": "Tesla, sans-serif",
        "body_font": "Tesla, sans-serif",
        "signature": "테슬라 빨강 + 전기차 = 혁신",
        "cluster": "neon-acid",
    },
    "theverge": {
        "primary": "#fa4b2a",
        "primary_active": "#d63920",
        "canvas": "#ffffff",
        "surface_card": "#f7f7f7",
        "ink": "#000000",
        "body": "#333333",
        "muted": "#999999",
        "headline_font": "Theinhardt, system-ui, sans-serif",
        "body_font": "Theinhardt, system-ui, sans-serif",
        "signature": "The Verge 주황 + 테크 뉴스 = 문화",
        "cluster": "colorful",
    },
    "together-ai": {
        "primary": "#00d9ff",
        "primary_active": "#00b8d9",
        "canvas": "#ffffff",
        "surface_card": "#f0f9fc",
        "ink": "#0d1b2a",
        "body": "#1b4965",
        "muted": "#5a7d99",
        "headline_font": "Inter, system-ui, sans-serif",
        "body_font": "Inter, system-ui, sans-serif",
        "signature": "청록색 + 협력 LLM = AI 커뮤니티",
        "cluster": "corporate-blue",
    },
    "uber": {
        "primary": "#000000",
        "primary_active": "#1a1a1a",
        "canvas": "#ffffff",
        "surface_card": "#f5f5f5",
        "ink": "#000000",
        "body": "#333333",
        "muted": "#999999",
        "headline_font": "Uber, sans-serif",
        "body_font": "Uber, sans-serif",
        "signature": "검은색 + 모빌리티 = 어디나",
        "cluster": "dark-minimal",
    },
    "vercel": {
        "primary": "#000000",
        "primary_active": "#1a1a1a",
        "canvas": "#ffffff",
        "surface_card": "#f5f5f5",
        "ink": "#000000",
        "body": "#333333",
        "muted": "#999999",
        "headline_font": "Inter, system-ui, sans-serif",
        "body_font": "Inter, system-ui, sans-serif",
        "signature": "검은색 + 웹 배포 = 현대식 호스팅",
        "cluster": "dark-minimal",
    },
    "vodafone": {
        "primary": "#e60000",
        "primary_active": "#b30000",
        "canvas": "#ffffff",
        "surface_card": "#f5f5f5",
        "ink": "#000000",
        "body": "#333333",
        "muted": "#999999",
        "headline_font": "Vodafone, sans-serif",
        "body_font": "Vodafone, sans-serif",
        "signature": "Vodafone 빨강 + 통신 = 연결",
        "cluster": "neon-acid",
    },
    "voltagent": {
        "primary": "#ff6b35",
        "primary_active": "#d64429",
        "canvas": "#0a0a0a",
        "surface_card": "#1a1a1a",
        "ink": "#ffffff",
        "body": "#d0d0d0",
        "muted": "#808080",
        "headline_font": "Inter, system-ui, sans-serif",
        "body_font": "Inter, system-ui, sans-serif",
        "signature": "주황색 + AI 에이전트 = 뜨거운 실행",
        "cluster": "dark-minimal",
    },
    "warp": {
        "primary": "#01a4ff",
        "primary_active": "#0088d9",
        "canvas": "#0a0e27",
        "surface_card": "#1a1f3a",
        "ink": "#ffffff",
        "body": "#d0d5e0",
        "muted": "#808a9a",
        "headline_font": "Inter, system-ui, sans-serif",
        "body_font": "Inter, system-ui, sans-serif",
        "signature": "Warp 파랑 + AI 터미널 = 속도",
        "cluster": "dark-minimal",
    },
    "webflow": {
        "primary": "#4353ff",
        "primary_active": "#3540d1",
        "canvas": "#ffffff",
        "surface_card": "#f5f7fb",
        "ink": "#000000",
        "body": "#333333",
        "muted": "#999999",
        "headline_font": "Inter, system-ui, sans-serif",
        "body_font": "Inter, system-ui, sans-serif",
        "signature": "Webflow 보라 + 웹 빌더 = 창의",
        "cluster": "corporate-blue",
    },
    "wired": {
        "primary": "#000000",
        "primary_active": "#1a1a1a",
        "canvas": "#ffffff",
        "surface_card": "#f5f5f5",
        "ink": "#000000",
        "body": "#333333",
        "muted": "#999999",
        "headline_font": "Pangram, system-ui, sans-serif",
        "body_font": "Pangram, system-ui, sans-serif",
        "signature": "검은색 + 기술 저널리즘 = 문화",
        "cluster": "dark-minimal",
    },
    "wise": {
        "primary": "#00b8d4",
        "primary_active": "#0099bb",
        "canvas": "#ffffff",
        "surface_card": "#f0f9fc",
        "ink": "#000000",
        "body": "#333333",
        "muted": "#999999",
        "headline_font": "Inter, system-ui, sans-serif",
        "body_font": "Inter, system-ui, sans-serif",
        "signature": "Wise 청록 + 국제 송금 = 신뢰",
        "cluster": "corporate-blue",
    },
    "x-ai": {
        "primary": "#000000",
        "primary_active": "#1a1a1a",
        "canvas": "#ffffff",
        "surface_card": "#f5f5f5",
        "ink": "#000000",
        "body": "#333333",
        "muted": "#999999",
        "headline_font": "Inter, system-ui, sans-serif",
        "body_font": "Inter, system-ui, sans-serif",
        "signature": "검은색 + AI 언어 모델 = X (구 Twitter)",
        "cluster": "dark-minimal",
    },
    "zapier": {
        "primary": "#ff4f00",
        "primary_active": "#d63d00",
        "canvas": "#ffffff",
        "surface_card": "#f8f8f8",
        "ink": "#0d0d0d",
        "body": "#333333",
        "muted": "#999999",
        "headline_font": "Inter, system-ui, sans-serif",
        "body_font": "Inter, system-ui, sans-serif",
        "signature": "Zapier 주황 + 자동화 = 연결",
        "cluster": "colorful",
    },
}

CLUSTERS = {
    "dark-minimal": [
        "apple",
        "binance",
        "clickhouse",
        "cursor",
        "expo",
        "hashicorp",
        "ibm",
        "kraken",
        "nike",
        "notion",
        "ollama",
        "opencode-ai",
        "posthog",
        "raycast",
        "replicate",
        "resend",
        "revolut",
        "runwayml",
        "sentry",
        "spacex",
        "spotify",
        "uber",
        "vercel",
        "voltagent",
        "warp",
        "wired",
        "x-ai",
    ],
    "warm-editorial": [
        "claude",
        "starbucks",
    ],
    "neon-acid": [
        "bmw-m",
        "bugatti",
        "ferrari",
        "lamborghini",
        "mastercard",
        "mongodb",
        "pinterest",
        "tesla",
        "vodafone",
    ],
    "corporate-blue": [
        "airtable",
        "bmw",
        "cal",
        "clay",
        "cohere",
        "coinbase",
        "figma",
        "framer",
        "intercom",
        "linear-app",
        "meta",
        "minimax",
        "mistral-ai",
        "playstation",
        "renault",
        "slack",
        "stripe",
        "together-ai",
        "webflow",
        "wise",
    ],
    "colorful": [
        "airbnb",
        "composio",
        "elevenlabs",
        "lovable",
        "mintlify",
        "miro",
        "nvidia",
        "sanity",
        "shopify",
        "superhuman",
        "supabase",
        "theverge",
        "zapier",
    ],
}

USE_CASES = {
    "lecture-docx": "claude",
    "exec-dashboard": "stripe",
    "dev-docs": "linear-app",
    "saas-landing": "airbnb",
    "data-viz": "mongodb",
    "fintech": "stripe",
    "corporate": "ibm",
    "consumer": "spotify",
}


def get_brand(name: str) -> dict:
    """name (lowercase, dashed) → token dict or fallback to 'claude'."""
    normalized = name.lower().replace(".", "-").replace("_", "-")
    return BRAND_TOKENS.get(normalized, BRAND_TOKENS["claude"])


def get_use_case(use_case: str) -> dict:
    """use_case → brand tokens."""
    brand_name = USE_CASES.get(use_case, "claude")
    return get_brand(brand_name)


def list_brands() -> list:
    """List all available brand names."""
    return sorted(BRAND_TOKENS.keys())


def list_clusters() -> dict:
    """List all clusters with member brands."""
    return CLUSTERS


if __name__ == "__main__":
    import json
    import sys
    if len(sys.argv) > 1:
        print(json.dumps(get_brand(sys.argv[1]), ensure_ascii=False, indent=2))
    else:
        print(f"{len(BRAND_TOKENS)} brands · {len(CLUSTERS)} clusters")
        for cluster, brands in sorted(CLUSTERS.items()):
            print(f"  {cluster}: {len(brands)} brands")
