@echo off
chcp 65001 >nul
setlocal
rem =====================================================
rem codex.bat - Codex AI worker (Windows)
rem
rem Usage:
rem   codex.bat                     Interactive mode
rem   codex.bat --auto              Auto (reads task-instruction.md)
rem   codex.bat --auto [task-file]  Auto with custom task file
rem   codex.bat --full-auto         Fully automated, no prompts
rem   codex.bat --analyze           Source analysis mode
rem
rem NOTE: Even with bypass permissions, this script ALWAYS
rem       asks for confirmation before modifying existing files.
rem =====================================================

set ROOT=%CD%
set TASK_FILE=%ROOT%\.claude\tasks\task-instruction.md
set MODE=interactive
set CONFIRM_MODIFY=true

rem --- Parse args ---
:PARSE_ARGS
if "%~1"=="" goto START
if /i "%~1"=="--auto"       ( set MODE=auto        & shift & goto PARSE_ARGS )
if /i "%~1"=="--full-auto"  ( set MODE=full-auto   & shift & goto PARSE_ARGS )
if /i "%~1"=="--analyze"    ( set MODE=analyze     & shift & goto PARSE_ARGS )
if /i "%~1"=="--no-confirm" ( set CONFIRM_MODIFY=false & shift & goto PARSE_ARGS )
if exist "%~1"              ( set TASK_FILE=%~1    & shift & goto PARSE_ARGS )
shift & goto PARSE_ARGS

:START
echo.
echo ============================================================
echo   Codex Worker
echo   Mode          : %MODE%
echo   Confirm modify: %CONFIRM_MODIFY%
echo ============================================================

rem ─── Interactive mode ───────────────────────────────────────
if "%MODE%"=="interactive" (
  echo [Codex] Interactive session...
  echo [NOTE]  Codex may ask to modify files - review carefully
  codex --dangerously-skip-permissions
  goto END
)

rem ─── Analyze mode ───────────────────────────────────────────
if "%MODE%"=="analyze" (
  echo [Codex] Source analysis mode
  echo         Will map code, find patterns, suggest improvements
  echo         DB/Query files: read-only, suggest only
  echo.

  if "%CONFIRM_MODIFY%"=="true" (
    echo [SAFETY] Before modifying any existing file,
    echo          Codex will show you the change and ask for confirmation.
    echo.
  )

  rem CLAUDE.md §7-1 준수: task-instruction.md 없이 codex 호출 금지
  rem analyze 모드 전용 task 파일 자동 생성 후 codex 가 그것을 읽도록
  set "ANALYZE_TASK=%ROOT%\.claude\tasks\task-codex-analyze.md"
  if not exist "%ROOT%\.claude\tasks" mkdir "%ROOT%\.claude\tasks" >nul 2>&1
  (
    echo # Task: Project Source Analysis ^(auto-generated by codex.bat --analyze^)
    echo.
    echo ## Goal
    echo Analyze the entire project source code and produce a structured report.
    echo.
    echo ## Steps
    echo 1. Read docs\project-analysis.md for stack context ^(if exists^).
    echo 2. Map all source files: list each file with its role ^(component/service/controller/model/etc^).
    echo 3. Identify patterns: state management, API call patterns, auth flow, error handling.
    echo 4. Find improvements: list specific issues in frontend and backend with file+line references.
    echo 5. For any .sql / query / mapper files, DO NOT MODIFY. Describe what they do, write suggested optimizations to docs\query-suggestions.md.
    echo 6. Write complete analysis to docs\codex-analysis.md.
    echo.
    echo ## Rules
    echo - Relative paths only ^(no hardcoded user paths^).
    echo - Before modifying any existing file, show planned change and ask 'OK to apply? ^(Y/N^)'.
    echo - New file creation does not need confirmation.
    echo - Follow all rules in CLAUDE.md.
  ) > "%ANALYZE_TASK%"

  codex --dangerously-skip-permissions "Read %ANALYZE_TASK% and execute every step in order."
  goto END
)

rem ─── Auto / Full-auto modes ─────────────────────────────────
if not exist "%TASK_FILE%" (
  echo [ERROR] Task file not found: %TASK_FILE%
  echo         Create task-instruction.md first
  echo         Or run: codex.bat  (interactive)
  exit /b 1
)

echo [Codex] Task: %TASK_FILE%
echo.
echo --- Task Preview (first 5 lines) ---
set LINE=0
for /f "tokens=*" %%L in ('type "%TASK_FILE%"') do (
  set /a LINE+=1
  if !LINE! LEQ 5 echo   %%L
)
echo ------------------------------------
echo.

rem --- HITL Approval Gate (CLAUDE.md §7-23) — 단발 호출도 위험 패턴 차단 ---
findstr /R /I /C:"DROP[ ]*TABLE" /C:"rm -rf" /C:"git push --force" /C:"sudo " /C:"curl .* | .*bash" /C:"--auto-approve" /C:"npm publish" /C:"docker push" "%TASK_FILE%" >nul 2>&1
if not errorlevel 1 (
  echo [HITL BLOCK] 위험 패턴 감지 — approval-gate 통과 후 재시도
  for %%F in ("%TASK_FILE%") do (
    python "%ROOT%\.claude\scripts\approval-gate.py" request "%%~nF" "%%~nxF" "auto-detected" "codex.bat 단발 task 본문 위험 패턴" 2>nul
  )
  echo         Run: /approve ^<task_id^>  ^(or /reject ^<task_id^>^)
  exit /b 3
)


rem Safety confirmation prompt for full-auto
if "%CONFIRM_MODIFY%"=="true" (
  echo [SAFETY] Codex will ask for confirmation before modifying
  echo          any EXISTING file. New files can be created freely.
  echo.
)

set PROMPT=Read the task instruction at %TASK_FILE% and implement everything described. Follow all constraints. IMPORTANT: Before modifying any existing file, show what you plan to change and ask 'OK to apply? (Y/N)'. New file creation does not need confirmation. After implementation write docs\implementation-report.md.

if "%MODE%"=="full-auto" (
  echo [Codex] Full-auto mode starting...
  codex --dangerously-skip-permissions --approval-mode full-auto "%PROMPT%"
) else (
  echo [Codex] Auto mode starting...
  codex --dangerously-skip-permissions "%PROMPT%"
)

echo.
echo [DONE] Codex complete
echo        Next: haiku-auto ^(default verifier per route_dispatch.md §7^)
echo        Or:   .claude\scripts\gemini.bat --verify ^(for ^>500k context^)

:END
endlocal
